name: Build and deploy Node.js app to Azure Web App - swiftcar-FE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          $env:CI="false" # Setting CI to false for PowerShell
          npm run build --if-present # Prevent treating warnings as errors
          npm run test -- --passWithNoTests
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build/ # Specify the path where your app is built (e.g., 'build' for React)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A4BABC4FDE2E49F885FCBF0747D64041 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD0F4977F6D1468790B64F34ACE837D7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_161684D3899D4850A8DE01B002DE6361 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'swiftcar-FE'
          slot-name: 'Production'
          package: build/ # Deploy the built folder
